### PR TITLE
Execute tools in correct working directory

### PR DESCRIPTION
**Pull request by niansa**

### CODE REVIEW

**Comment by SergiusTheBest** [comment]
@niansa Thank you for the PR! Could you describe the issue it fixes?

**Comment by niansa** [comment]
For me it isn't able to find other included idl's that are located next to the main idl without this.

**Comment by SergiusTheBest** [comment]
@niansa Yeah, it makes sense. Let me check that.

**Comment by SergiusTheBest** [comment]
@niansa Yes, it's working now. Thank you!

**Pull request merged**
